# Generated by Django 5.0.6 on 2025-05-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bely_works', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
