# Generated by Django 5.0.6 on 2025-05-09 23:28

import works.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bely_works', '0004_alter_userprofile_options_user_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=works.models.user_avatar_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
