# Generated by Django 4.2 on 2025-03-24 11:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bely_works', '0004_alter_article_options_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='ProductAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Автор'), ('ILLUSTRATOR', 'Иллюстратор'), ('TRANSLATOR', 'Переводчик')], max_length=50)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bely_works.author')),
            ],
            options={
                'verbose_name': 'Автор продукта',
                'verbose_name_plural': 'Авторы продуктов',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_date',
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.AddField(
            model_name='productauthor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bely_works.product'),
        ),
        migrations.AddField(
            model_name='author',
            name='products',
            field=models.ManyToManyField(related_name='authors', through='bely_works.ProductAuthor', to='bely_works.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productauthor',
            unique_together={('product', 'author', 'role')},
        ),
    ]
