# Generated by Django 5.0.6 on 2025-05-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bely_works', '0008_cart_is_active_alter_cart_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
    ]
