# Generated by Django 5.0.6 on 2025-05-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bely_works', '0009_alter_cart_options_alter_cartitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
