# Generated by Django 5.0.6 on 2025-05-31 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bely_works', '0011_alter_article_options_remove_product_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('url', models.URLField(verbose_name='URL ресурса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tags', models.CharField(help_text='Теги через запятую', max_length=500, verbose_name='Теги')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL источника'),
        ),
        migrations.AddField(
            model_name='product',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL сайта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bely_works.category', verbose_name='Категория'),
        ),
    ]
