# Generated by Django 5.0.6 on 2025-06-23 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bely_works', '0012_resource_article_source_url_product_website_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mdexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('exam_date', models.DateTimeField(verbose_name='Дата проведения экзамена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exams/', verbose_name='Задание (картинка)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('users', models.ManyToManyField(related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
            },
        ),
    ]
